---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-update-git-ogawa-github-io-v1beta1-docserver
  failurePolicy: Fail
  name: mdocserver.kb.io
  rules:
  - apiGroups:
    - update.git-ogawa.github.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - docservers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-update-git-ogawa-github-io-v1beta1-docserver
  failurePolicy: Fail
  name: vdocserver.kb.io
  rules:
  - apiGroups:
    - update.git-ogawa.github.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - docservers
  sideEffects: None
