apiVersion: v1
kind: Service
metadata:
  name: {{ include "docserver.fullname" . }}-webhook-service
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: docserver
    app.kubernetes.io/part-of: docserver
  {{- include "docserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
  {{- include "docserver.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}