# permissions for end users to view docservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: docserver-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: docserver
    app.kubernetes.io/part-of: docserver
    app.kubernetes.io/managed-by: kustomize
  name: docserver-viewer-role
rules:
- apiGroups:
  - update.git-ogawa.github.io
  resources:
  - docservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - update.git-ogawa.github.io
  resources:
  - docservers/status
  verbs:
  - get
