name: Build and push gitpod image.

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag and set version
        run: |
          VERSION=$(eval echo ${GITHUB_REF#refs/*/} | tr -d v)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and push images
        uses: docker/build-push-action@v3
        with:
          context: images/gitpod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: docogawa/gitpod:latest,docogawa/gitpod:${{ env.VERSION }}
